CV_Project2022/Pages/BrowseCv.cshtml.cs
using CV_Project2022.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class BrowseCvModel : PageModel
    {

        private readonly DBService _service;

        public BrowseCvModel(DBService service)
        {
            _service = service;
        }

        public ViewModel viewModel { get; set; } = new ViewModel();
         public List<CvModel> CV_list { get; private set; }

        public async Task OnGet()
        {
            viewModel.CV_list = await _service.GetAllCVs();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {

            await _service.DeleteCv(id);

            return RedirectToPage("BrowseCv");
        }
    }
}

CV_Project2022/Pages/EditCV.cshtml.cs
using CV_Project2022.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class EditCVModel : PageModel
    {
        private readonly DBService _service;
        private readonly OtherService _otherService;

        public EditCVModel(DBService service, OtherService otherService)
        {
            _service = service;
            _otherService = otherService;
        }


        [BindProperty]
        public CvModel Input { get; set; } = new CvModel();

        public ViewModel viewModel { get; set; } = new ViewModel();

        public async Task OnGetAsync(int id)
        {
            // Get cv having this id from database
            Input = await _service.GetCvById(id);

            List<SelectListItem> selected_skills = Input.Skills;

            // Get the all skills from database
            List<SkillModel> skillModel_list = await _service.GetAllSkills();

            // fill the viewModel skills list
            viewModel.skills_list = _otherService.GetSkills(skillModel_list);

            // fill the input with all the skills from database
            Input.Skills = viewModel.skills_list;

            if (selected_skills.Count == 0)
            {
                for (int i = 0; i < viewModel.skills_list.Count; i++)
                {
                    Input.Skills[i].Selected = false;
                }
            }
            else
            {
                // get the skills selected by the user to be checked
                for (int i = 0; i < viewModel.skills_list.Count; i++)
                {
                    for (int j = 0; j < selected_skills.Count; j++)
                    {
                        if (Input.Skills[i].Text.Equals(selected_skills[j].Text))
                        {
                            Input.Skills[i].Selected = true;
                            break;
                        }
                    }
                }

            }
     
        }

        public async Task<IActionResult> OnPost(int id)
        {
            if (!ModelState.IsValid)
            {
                // Get the skills from database
                List<SkillModel> skillModel_list = await _service.GetAllSkills();

                // fill the viewModel skills list
                viewModel.skills_list = _otherService.GetSkills(skillModel_list);

                return Page();
            }

            Input.Id = id;

            // Update Database
            await _service.UpdateCv(Input);

            return RedirectToPage("ViewCv",new {id=id});
        }

        public IActionResult OnPostReturn(int id)
        {
            return RedirectToPage("BrowseCv");
        }
    }
}

CV_Project2022/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CV_Project2022/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CV_Project2022.Pages
{
    public class HomeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CV_Project2022/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public RedirectToPageResult OnGet()
        {
            return RedirectToPage("Home");
        }
    }
}

CV_Project2022/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CV_Project2022/Pages/SendCV.cshtml.cs
using CV_Project2022.Data;
using CV_Project2022.FileUploadService;
using CV_Project2022.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class SendCVModel : PageModel
    {
 
        private readonly DBService _service;
        private readonly OtherService _otherService;

        public SendCVModel(DBService service , OtherService otherService)
        {  
           _service = service;
           _otherService = otherService;
        }


        [BindProperty]
        public CvModel Input { get; set; } = new CvModel();

        public ViewModel viewModel { get; set; } = new ViewModel();

        public async void OnGet()
        {
            // Get the skills from database
            List<SkillModel> skillModel_list = await _service.GetAllSkills();

            // fill the viewModel skills list
            viewModel.skills_list = _otherService.GetSkills(skillModel_list);

            // Checkboxes first --> not checked 
            Input.Skills = viewModel.skills_list;

            // Calculate random numbers for verification
            Random rnd = new Random();
            int nb1 = rnd.Next(1, 21);   // 1 <= nb1 < 21
            int nb2 = rnd.Next(20, 51);  // 20 <= nb2 < 51

            Input.FirstNb = nb1;
            Input.SecondNb = nb2;
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                // Get the skills from database
                List<SkillModel> skillModel_list = await _service.GetAllSkills();

                // fill the viewModel skills list
                viewModel.skills_list = _otherService.GetSkills(skillModel_list);

                return Page();
            }

            int TrueResult = Input.FirstNb + Input.SecondNb;

            if (TrueResult != Input.Summation)
            {
                ModelState.AddModelError(String.Empty , "Incorrect answer! Please Try again...");

                // Get the skills from database
                List<SkillModel> skillModel_list = await _service.GetAllSkills();

                // fill the viewModel skills list
                viewModel.skills_list = _otherService.GetSkills(skillModel_list);

                return Page();
            }

            // Insert into Database
            await _service.AddNewCv(Input);

            return RedirectToPage("BrowseCv");
 
        }


    }
}

CV_Project2022/Pages/ViewCV.cshtml.cs
using CV_Project2022.FileUploadService;
using CV_Project2022.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace CV_Project2022.Pages
{
    public class ViewCVModel : PageModel
    {
        private readonly DBService _service;
        private readonly OtherService _otherService;
        private readonly IFileUploadService _fileUploadService;

        public ViewCVModel(DBService service, OtherService otherService, IFileUploadService fileUploadService)
        {
            _service = service;
            _otherService = otherService;
            _fileUploadService = fileUploadService;
        }

        public ViewModel viewModel { get; set; } = new ViewModel();
        public int id;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            viewModel.CV = await _service.GetCvById(id);

            return Page();
        }

       

        
    }
}

CV_Project2022/Pages/BrowseCv.cshtml
@page
@model CV_Project2022.Pages.BrowseCvModel
@{
    ViewData["Title"] = "All CVs";
}

<h1 class="subtitle"> @ViewData["Title"] </h1>

<a asp-page="SendCV" class="btn btn-primary addbtn">Add new CV</a>

<div class="row">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Grade</th>
                    <th class="align-middle"></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var c in Model.viewModel.CV_list)
                {
                    <tr>
                        <td class="align-middle">@c.FirstName</td>
                        <td class="align-middle">@c.LastName</td>
                        <td class="align-middle">@c.Email</td>
                        <td class="align-middle">@c.Gender</td>
                        <td class="align-middle">@c.Grade</td>

                        <td class="align-middle">
                            <form class="actionBtns" method="post" class="align-middle">
                                <a asp-page="/ViewCV" asp-route-id="@c.Id" class="btn btn-success">Details</a>
                        
                                <a asp-page="/EditCV" asp-route-id="@c.Id" class="btn btn-warning">Edit</a>
                            
                                <button type="submit" asp-page-handler="Delete" asp-route-id="@c.Id" class="btn btn-danger" id="deletebtn">Delete</button>

                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CV_Project2022/Pages/EditCV.cshtml
@page "{id}"
@model CV_Project2022.Pages.EditCVModel
@{
    ViewData["Title"] = "Edit CV";
}

<div class="container">

    <h1 class="subtitle">Edit CV</h1>

    <form class="Sendform" method="post" enctype="multipart/form-data">
        
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.FirstName"></label>
                <input class="form-control" asp-for="@Model.Input.FirstName" />
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.LastName"></label>
                <input class="form-control" asp-for="@Model.Input.LastName" />
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Date"></label>
                <input class="form-control" asp-for="@Model.Input.Date" />
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Nationality"></label>
                <select class="form-control dropdown" asp-for="@Model.Input.Nationality" asp-items="@Model.viewModel.nationality_list" >
                    <option value="">**Not Selected**</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label>Gender:</label> 
            @foreach(var gender in Model.viewModel.gender_list){
                <input class="gender" type="radio" asp-for="@Model.Input.Gender" value="@gender" />@gender
            }
        </div>

        <div class="form-group">
            <label asp-for="@Model.Input.Skills"></label>
            <ul class="checkboxes">
                @for(int i=0; i < Model.viewModel.skills_list.Count; i++){
                    <li>
                       <input type="hidden" asp-for="@Model.Input.Skills[i].Value" />
                       <input type="hidden" asp-for="@Model.Input.Skills[i].Text" />
                       <input  class="checkbox" asp-for="Input.Skills[i].Selected" /> @Model.viewModel.skills_list[i].Text
                    </li>
                }
            </ul>         
        </div>
        
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Photo"></label>
                <input class="form-control file" type="file" asp-for="@Model.Input.Photo" accept="image/*" />
            </div>
        </div>

         <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Email"></label>
                <input class="form-control" asp-for="@Model.Input.Email" />
            </div>


            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.ConfirmEmail"></label>
                <input class="form-control" asp-for="@Model.Input.ConfirmEmail" />
            </div>
        </div>

        <div asp-validation-summary="All" class="text-danger"></div> 
        
        <button type="submit" asp-route-id=@Model.Input.Id class="btn btn-primary">Update</button>
        <button type="submit" asp-page-handler="Return"  class="btn btn-secondary">Cancel</button>

    </form>

</div>

CV_Project2022/Pages/Home.cshtml
@page
@model CV_Project2022.Pages.HomeModel
@{
    ViewData["Title"] = "Home";
}

<div class="container">
    <h1 class="text-center">The fast & visual way to manipulate CVs</h1>

    <img class="HomeBG" src="/images/HomeBG.png" >
</div>

CV_Project2022/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Index";
}

CV_Project2022/Pages/SendCV.cshtml
@page
@model CV_Project2022.Pages.SendCVModel
@{
    ViewData["Title"] = "Send CV";
}

<div class="container">

    <h1 class="subtitle">Send CV</h1>

    <form class="Sendform" method="post" enctype="multipart/form-data">
        
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.FirstName"></label>
                <input class="form-control" asp-for="@Model.Input.FirstName" />
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.LastName"></label>
                <input class="form-control" asp-for="@Model.Input.LastName" />
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Date"></label>
                <input class="form-control" asp-for="@Model.Input.Date" />
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Nationality"></label>
                <select class="form-control dropdown" asp-for="@Model.Input.Nationality" asp-items="@Model.viewModel.nationality_list" >
                    <option value="">**Not Selected**</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label>Gender:</label> 
            @foreach(var gender in Model.viewModel.gender_list){
                <input class="gender" type="radio" asp-for="@Model.Input.Gender" value="@gender" />@gender
            }
        </div>

        <div class="form-group">
            <label asp-for="@Model.Input.Skills"></label>
            <ul class="checkboxes">
                @for(int i=0; i < Model.viewModel.skills_list.Count; i++){
                    <li>
                       <input type="hidden" asp-for="@Model.Input.Skills[i].Value" />
                       <input  class="checkbox" asp-for="Input.Skills[i].Selected" /> @Model.viewModel.skills_list[i].Text
                    </li>
                }
            </ul>         
        </div>
        
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Photo"></label>
                <input class="form-control file" type="file" asp-for="@Model.Input.Photo" accept="image/*" />
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.Email"></label>
                <input class="form-control" asp-for="@Model.Input.Email" />
            </div>


            <div class="form-group col-md-6">
                <label asp-for="@Model.Input.ConfirmEmail"></label>
                <input class="form-control" asp-for="@Model.Input.ConfirmEmail" />
            </div>
        </div>

        <label>Verification</label> <br />

        <p>Before you proceed please enter the summation.</p>

        <div class="row">
            <div class="form-group col-md-3">
                <input class="form-control" asp-for="@Model.Input.FirstNb" readonly /> 
            </div>

            +

            <div class="form-group col-md-3">
                <input class="form-control" asp-for="@Model.Input.SecondNb" readonly /> 
            </div>

            =

            <div class="form-group col-md-3">
                <input class="form-control" asp-for="@Model.Input.Summation" />
            </div>

        </div>

        <div asp-validation-summary="All" class="text-danger"></div> 
        
        <button type="submit" class="btn btn-primary">Send</button>

    </form>

    


</div>

CV_Project2022/Pages/ViewCV.cshtml
@page "{id}"
@model CV_Project2022.Pages.ViewCVModel
@{
    ViewData["Title"] = "Summary CV";
}

<div class="container" align="center" >

    
    <div class="top">
        <a asp-page="BrowseCv"><iconify-icon inline icon="akar-icons:arrow-back-thick" style="color: darkblue;" width="40" height="40"></iconify-icon></a> 
        <button class="btn btn-primary" onclick="PrintDiv(CVSummary);">Generate PDF</button>
    </div>

    <div class="CVcard" id="CVSummary" >

        <div class="personalInfo">
            <img src="~/images/@Model.viewModel.CV.Photo.FileName" />
            <h3 class="text-primary text-capitalize pdfbtn" id="NAME">@Model.viewModel.CV.FirstName @Model.viewModel.CV.LastName</h3>
        </div>

        <table class="table">
            <tr>
                <td class="font-weight-bold">Date of Birth:</td>
                <td>@Model.viewModel.CV.Date</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Gender:</td>
                <td>@Model.viewModel.CV.Gender</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Nationality:</td>
                <td>@Model.viewModel.CV.Nationality</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Email:</td>
                <td>@Model.viewModel.CV.Email</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Skills:</td>
                <td>
                    @if(!Model.viewModel.CV.Skills.Any()){
                        <span class="skill" >** No selected skills **</span>
                    }
                    else
                    {
                        @foreach(var s in Model.viewModel.CV.Skills){
                            <span class="skill" >@s.Text</span>
                        } 
                    }
                               
                </td>
            </tr>
        </table>

        <div class="grade btn-primary">
            Grade : @Model.viewModel.CV.Grade
        </div>

    </div>

   
</div>

<script>
    function PrintDiv(div) {
        html2canvas((div), {
            onrendered: function (canvas) {
                var imageData = canvas.toDataURL("image/jpeg", 1.0);

                var pdf = new jsPDF('l', 'mm', [297, 210]);
                pdf.addImage(imageData, 'JPEG', 70, 5);
                pdf.save("CV.pdf");
            }
        });
    }
</script>